### ISSUE TITLE
Section Header Links

### ISSUE THREAD

**Issue by smerrell** [FubuMvcArchive/FubuDocs#37]
One thing I noticed different from what we were doing with ReadTheDocs and FubuDocs is that ReadTheDocs automatically puts an anchor by each paragraph. That way you can reference a section directly. This could be useful to add to FubuDocs. Though I'm not sure how easy that'd be to add.

![screen shot 2013-10-04 at 3 07 43 pm](https://f.cloud.github.com/assets/167781/1272881/292b132a-2d39-11e3-9a9e-30b3e3be649b.png)

**Comment by storyteller** [comment]
It doesn't already do that?  Not that big of a deal to add if it doesn't.

**Comment by smerrell** [comment]
I just noticed that you have a Spark binding to do sections. I was referring to when using markdown syntax but I'm guessing that'd be pretty difficult to do it from that. I'll let you know if it is working when I replace the markdown syntax with <Section>

**Comment by smerrell** [comment]
So it looks like there is the `<Section>` binding that can be done and it ends up using the [SectionTag](https://github.com/DarthFubuMVC/FubuDocs/blob/b838e56ffa6e88eb0fd94ccfc96b1e644637155d/src/FubuDocs/Navigation/SectionTag.cs) which just gives it an `H4` with an id. RTD actually ends up putting an `a` tag in the heading like this

``` html
<a class="headerlink" href="#meet-the-allowroleattribute" title="Permalink to this headline">¶</a>
```

I'd love for it to be able to do that without having to use the `<Section>` tag and keep it to Markdown, but that might be pretty difficult to do. At least in the short term, it'd be nice if the SectionTag added the a tag in the header.

**Comment by jeremydmiller** [comment]
Sam,

That SectionTag and spark binding was driven by the left navigation and the TwitterBootstrap plugin.  I might be wrong, but I'm pretty sure that that plugin required <Section> tags.

**Comment by jeremydmiller** [comment]
@smerrell,

Unless we wanna investigate a Markdown extension w/ Spark, I think we're just going to have to live with this one.
