### ISSUE TITLE
Snippet / Sample Inconsistency

### ISSUE THREAD

**Issue by smerrell** [FubuMvcArchive/FubuDocs#39]
Including Snippets/Samples in the docs uses the `<Snippet>` spark binding, but to declare a Snippet/Sample in code uses the SAMPLE: `<name>` / ENDSAMPLE format. We probably should make that consistent between the two.

I have already tried doing // SNIPPET: `<name>` a few times on Friday. :)

**Comment by jeremydmiller** [comment]
Meh, wanna just have it doubled up?  It'd be in FubuMVC.CodeSnippets, not here.

**Comment by smerrell** [comment]
I'm ok with it being doubled up. I opened DarthFubuMVC/FubuMVC.CodeSnippets#21 for this
